/**
 * Represents a product in the inventory.
 * Used throughout Produits pages, sales forms, and dashboard widgets.
 */
export interface Product {
  /** Unique identifier (e.g. "P1", auto-generated by json-server). */
  id: string;
  /** Product name / designation (French: "désignation"). */
  design: string;
  /** Product category (e.g. "Électronique", "Informatique"). */
  category: string;
  /** Current quantity in stock. Decremented when a sale is recorded. */
  stock: number;
  /** Unit price in EUR. */
  price: number;
}

/**
 * Represents a customer / client.
 * Managed via the Clients feature (CRUD + bulk delete).
 */
export interface Client {
  /** Unique identifier (e.g. "C1"). */
  id: string;
  /** Full name of the client (French: "nom"). */
  nom: string;
  /** Email address. */
  email: string;
  /** Phone number (French: "téléphone"). */
  telephone: string;
  /** Physical address (French: "adresse"). */
  adresse: string;
}

/**
 * Represents a sale / stock-out operation.
 * Each sale links a client to a product with a specified quantity.
 * Creating or modifying a sale also generates an {@link AuditEntry}.
 */
export interface Sale {
  /** Unique identifier (e.g. "S1"). */
  id: string;
  /** Foreign key → {@link Product.id}. */
  productId: string;
  /** Foreign key → {@link Client.id}. */
  clientId: string;
  /** Quantity taken out of stock (French: "quantité sortie"). */
  qteSortie: number;
  /** ISO 8601 date string of when the sale was recorded. */
  date: string;
  /** Current status: pending ("En attente"), validated ("Validé"), or cancelled ("Annulé"). */
  status: 'En attente' | 'Validé' | 'Annulé';
}

/**
 * Represents one row in the audit log.
 * Audit entries are **automatically created** by the {@link useVentes} hook
 * whenever a sale is added, modified, or deleted.
 */
export interface AuditEntry {
  /** Unique identifier (e.g. "A1"). */
  id: string;
  /** Type of CRUD operation: AJOUT (insert), MODIFICATION (update), SUPPRESSION (delete). */
  typeOperation: 'AJOUT' | 'MODIFICATION' | 'SUPPRESSION';
  /** Client name at the time of the operation (denormalized for history). */
  nomClient: string;
  /** Product name at the time of the operation (denormalized for history). */
  designProduit: string;
  /** Previous quantity before the change (0 for new sales). */
  qteSortieAncien: number;
  /** New quantity after the change (0 for deletions). */
  qteSortieNouv: number;
  /** ISO 8601 timestamp of when the audit entry was created (French: "date de mise à jour"). */
  dateMiseAJour: string;
  /** Name of the user who performed the operation. */
  utilisateur: string;
}
